package lab.mars.m2m.protocol.enumeration;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * Created by haixiao on 14/11/14.
 * according to_servAddr TS0004 v0.8.0
 */
@XmlEnum(Integer.class)
public enum m2m_execResultType {
    @XmlEnumValue("1")STATUS_REQUEST_UNSUPPORTED,
    @XmlEnumValue("2")STATUS_REQUEST_DENIED,
    @XmlEnumValue("3")STATUS_CANCELLATION_DENIED,
    @XmlEnumValue("4")STATUS_INTERNAL_ERROR,
    @XmlEnumValue("5")STATUS_INVALID_ARGUMENTS,
    @XmlEnumValue("6")STATUS_RESOURCES_EXCEEDED,
    @XmlEnumValue("9")STATUS_UNSUPPORTED_PROTOCOL,
    @XmlEnumValue("10")STATUS_UPLOAD_FAILED,
    @XmlEnumValue("11")STATUS_FILE_TRANSFER_FAILED_MULTICAST_GROUP_UNABLE_JOIN,
    @XmlEnumValue("12")STATUS_FILE_TRANSFER_FAILED_SERVER_CONTACT_FAILED,
    @XmlEnumValue("13")STATUS_FILE_TRANSFER_FAILED_FILE_ACCESS_FAILED,
    @XmlEnumValue("14")STATUS_FILE_TRANSFER_FAILED_DOWNLOAD_INCOMPLETE,
    @XmlEnumValue("15")STATUS_FILE_TRANSFER_FAILED_FILE_CORRUPTED,
    @XmlEnumValue("16")STATUS_FILE_TRANSFER_FILE_AUTHENTICATION_FAILURE,
    @XmlEnumValue("17")STATUS_FILE_TRANSFER_FAILED,
    @XmlEnumValue("18")STATUS_FILE_TRANSFER_SERVER_AUTHENTICATION_FAILURE,
    @XmlEnumValue("19")STATUS_FILE_TRANSFER_WINDOW_EXCEEDED,
    @XmlEnumValue("20")STATUS_INVALID_UUID_FORMAT,
    @XmlEnumValue("21")STATUS_UNKNOWN_EXECUTION_ENVIRONMENT,
    @XmlEnumValue("22")STATUS_DISABLED_EXECUTION_ENVIRONMENT,
    @XmlEnumValue("23")STATUS_EXECUTION_ENVIRONMENT_MISMATCH,
    @XmlEnumValue("24")STATUS_DUPLICATE_DEPLOYMENT_UNIT,
    @XmlEnumValue("25")STATUS_SYSTEM_RESOURCES_EXCEEDED,
    @XmlEnumValue("26")STATUS_UNKNOWN_DEPLOYMENT_UNIT,
    @XmlEnumValue("27")STATUS_INVALID_DEPLOYMENT_UNIT_STATE,
    @XmlEnumValue("28")STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_DOWNGRADE_DISALLOWED,
    @XmlEnumValue("29")STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_UPGRADE_DISALLOWED,
    @XmlEnumValue("30")STATUS_INVALID_DEPLOYMENT_UNIT_UPDATE_VERSION_EXISTS;
}
